<div class="container container-products">
    <div class="error-notifice">
        <?php foreach ($this->errors as $error): ?>
            <p>*<?php echo $error; ?></p>
        <?php endforeach; ?>
    </div>
    <form class="form-horizontal" action="/user/forgot" method="post">
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">Email:</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="email" placeholder="Enter email" required name="email">
            </div>
        </div>
        <div class="form-group"> 
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Reset password</button>
            </div>
        </div>
    </form>
</div>