<div class="container container-products">
	<tr id="user-<?php echo $this->user['id']; ?>" class="<?php echo $this->class; ?>">
		<td class="order"><?php echo $this->order; ?></td>
		<td class="id"><?php echo $this->user['id']; ?></td>
		<td class="name title"><?php echo $this->user['name']; ?></td>
		<td class="email"><?php echo $this->user['email']; ?></td>
		<td><a href="#edit" class="edit_object">Edit</a> <a href="#remove" class="remove_object">Remove</a></td>
	</tr>
</div>