<div class="container container-products">
    <div class="error-notifice">
        <?php foreach ($this->errors as $error): ?>
            <p>*<?php echo $error; ?></p>
        <?php endforeach; ?>
    </div>
    <form class="form-horizontal" action="/user/login" method="post">
        <div class="form-group">
            <label class="control-label col-sm-2" for="email">Email:</label>
            <div class="col-sm-10">
                <input type="email" class="form-control" id="email" placeholder="Nhập email" required name="email">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="pwd">Mật khẩu:</label>
            <div class="col-sm-10"> 
                <input type="password" class="form-control" id="pwd" placeholder="Nhập mật khẩu" required name="password">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2"> 
                <a href="/user/forgot">Quên mật khẩu?</a>
            </div>
        </div>
        <div class="form-group"> 
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Đăng nhập</button>
            </div>
        </div>
    </form>
</div>