<div class="container container-products">
    <div class="error-notifice">
        <?php foreach ($this->errors as $error):?>
            <p>*<?php echo $error; ?></p>
        <?php endforeach;?>
    </div>
    <form class="form-horizontal" action="/user/updatepassword" method="post">
        <input type="hidden" name="password" value="<?php echo $this->password; ?>">
        <div class="form-group">
            <label class="control-label col-sm-4" for="current_password">System generated password:</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="current_password" name="current_password" placeholder="Password is granted" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-4" for="new_password">New password:</label>
            <div class="col-sm-8">
                <input type="password" class="form-control" id="new_password" name="new_password" placeholder="New Password" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-4" for="repeat_password">Confirm new password:</label>
            <div class="col-sm-8"> 
                <input type="password" class="form-control" id="repeat_password" name="repeat_password" placeholder="Password confirm" required>
            </div>
        </div>
        <div class="form-group"> 
            <div class="col-sm-offset-4 col-sm-6">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
</div>