<div class="container container-products">
    <div class="form-horizontal" >
        <input type="hidden" name="id" value="<?php echo $this->user['id']; ?>">
        <div class="form-group">
            <label class="control-label col-sm-3" for="firstname">First name:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="firstname" name="firstname" disabled value="<?php echo $this->user['firstname']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="lastname">Last name:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="lastname" name="lastname" disabled value="<?php echo $this->user['lastname']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="website">User's personal Web page:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="website" disabled name="persional_website" value="<?php echo $this->user['persional_website']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="organization">Organization:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="organization" disabled name="organization" required value="<?php echo $this->user['organization']; ?>">
            </div>
        </div>

        <hr>
        <div class="form-group">
            <label class="control-label col-sm-3" for="phone">Phone:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="phone" disabled name="phone" value="<?php echo $this->user['phone']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="address">Address, line 1:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="address" disabled name="address" required value="<?php echo $this->user['address']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="address2">Address, line 2:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="address2" disabled name="address_2" value="<?php echo $this->user['address_2']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="city">City:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="city" disabled name="city" required value="<?php echo $this->user['city']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="postcode">Post code:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="postcode" disabled name="postcode" required value="<?php echo $this->user['postcode']; ?>">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="country">Country:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="country" disabled name="country" required value="<?php echo $this->user['country']; ?>">
            </div>
        </div>

        <hr>
        <div class="form-group">
            <label class="control-label col-sm-3" for="email">Email:</label>
            <div class="col-sm-9">
                <input type="email" class="form-control" id="email" disabled name="email" required value="<?php echo $this->user['email']; ?>">
            </div>
        </div>
        <hr>

        <div class="form-group">
            <label class="control-label col-sm-3" for="email">Type:</label>
            <div class="col-sm-9">
                <div class="checkbox">
                    <label><input type="checkbox" disabled name="chooseType" value="Authors" required value="<?php echo $this->user['chooseType']; ?>"> Authors</label>
                </div>
                <div class="checkbox">
                    <label><input type="checkbox" disabled name="chooseType" value="Reviewer" required value="<?php echo $this->user['chooseType']; ?>"> Reviewer</label>
                </div>
            </div>
        </div>
        <hr>
    </div>
</div>