<div class="container container-products">        
    <form class="form-horizontal signup" method="post" action="/user/create">
        <?php if($this->message != NULL):?>
            <div class="alert alert-danger">
              <?php echo $this->message;?>
          </div>
      <?php endif;?>
      <p>To use TraTienViet, you must agree to its Terms of Service (<a href="#">view terms</a>), (<a href="">download terms</a>)</p>
      <div class="form-group"> 
        <div class="col-sm-12">
            <div class="checkbox">
                <label><input type="checkbox" class="agree"> I agree to TraTienViet Terms of Service</label>
            </div>
        </div>
    </div>
    <hr>
    <p>Thông tin cơ bản</p>
    <div class="form-group">
        <label class="control-label col-sm-3" for="name">Tên(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="name" placeholder="Enter your name" name="name" required>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-3" for="telephone">Điện thoại:</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="telephone" placeholder="Enter your telephone" name="telephone">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-3" for="address">Địa chỉ(*):</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="address" placeholder="Enter your address" name="address" required>
        </div>
    </div>   
    <div class="form-group">
        <label class="control-label col-sm-3" for="email">Email (*):</label>
        <div class="col-sm-9">
            <input type="email" class="form-control" id="email" placeholder="Enter your email" name="email" required>
        </div>
    </div>

    <div class="form-group"> 
        <div class="col-sm-12">
            <button type="submit" class="btn btn-success center-block signup">TẠO TÀI KHOẢN</button>
        </div>
    </div>
</form>
</div>
<?php
echo $this->partial("layout/modal_notice.phtml", array('title' => 'Notice',));
?>