<form class="form-horizontal" id="newspaper" action="<?php echo $this->action; ?>">
    <input type="hidden" value="<?php echo $this->news['id']; ?>" name="id">
    <div class="form-group">
        <label class="control-label col-sm-2" for="title">Title:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="title" placeholder="Title news" name="title" required value="<?php echo $this->news['title']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="category">Category:</label>
        <div class="col-sm-10">
            <select class="form-control" id="category" name="category_id">
                <?php foreach ($this->categories as $category): ?>
                    <option value="<?php echo $category['id'] ?>" <?php if ($category['id'] == 19) echo 'selected'; ?>><?php echo $category['name']; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="title">Content:</label>
        <div class="col-sm-10">
            <div class="content">
                <?php echo $this->news['content']; ?>
            </div>
        </div>
    </div>

    <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-10">
            <div class="checkbox">
                <label><input type="checkbox" name="type" value="1" <?php if ($this->news['type'] == 1) echo 'checked'; ?>> News hot</label>
            </div>
        </div>
    </div>

    <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>
</form>



