<h1>
    Papers
</h1>
<div class="row"></div>
<table class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Papers</th>
            <!-- <th>Full paper status</th>
            <th>Reviewer</th> -->
        </tr>
    </thead>
    <tbody>
        <?php
        $order = 1;
        foreach ($this->users as $user):
            ?>
            <tr id="user-<?php echo $user['id']; ?>">
                <td><?php echo $order++; ?></td>
                <td class="id"><?php echo $user['id']; ?></td>
                <!-- <td class="name title"><a href="/user/show?id=<?php echo $user['id']; ?>"><?php echo $user['name']; ?></a></td> -->
                <td class="name title"><?php echo $user['name']; ?></td>
                <td class="email"><a href="mailto:<?php echo $user['email']; ?>"><?php echo $user['email']; ?></a></td>
                <td class="paper">
                    <?php foreach ($user['papers'] as $key => $paper): ?>
                        <p><!-- <?php echo ($key + 1); ?> --><span>- PID</span> <?php echo $paper['id']?>. <a href="/index/edit?id=<?php echo $paper['id']; ?>"><?php echo $paper['title']; ?></a>
                            <?php if($paper['type'] == 1): ?>
                                <span class="label label-success">Approved</span>
                            <?php elseif ($paper['type'] == 2): ?>
                                <span class="label label-danger">Reject</span>
                            <?php endif;?>
                        </p>
                        <p>Full paper status:
                            <?php if ($paper['fullPaper'] == NULL || $paper['fullPaper'] == '/uploads/papers/' . $paper['user_id'] . '/') { ?>
                            <span class="paperUpload">Not Available</span>                           
                            <?php } else { ?>                           
                            <span class="paperUpload">Submitted</span><br>
                            <?php } ?>
                        </p>
                        <p>Reviewer 1: 
                            <span class="paperUpload"><?php echo $paper['review1_name'] ?></span><br>
                        </p>
                        <p>Reviewer 2: 
                            <span class="paperUpload"><?php echo $paper['review2_name'] ?></span><br>
                        </p>
                    <?php endforeach; ?>
                </td>    
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


