<tr id="audio-<?php echo $this->audio['id']; ?>" class="<?php echo $this->class; ?>">
    <td class="order"><?php echo $this->order; ?></td>
    <td class="id"><?php echo $this->audio['id']; ?></td>
    <td class="name title"><?php echo $this->audio['name']; ?></td>
    <td class="link"><a target="_blank" href="<?php echo $this->audio['url']?>"><?php echo $this->audio['name'];?></a></td>
    <td><a href="#remove" class="remove_object">Remove</a></td>
</tr>