<form class="form-horizontal" id="newspaper" action="<?php echo $this->action; ?>" data-name="category">
    <input type="hidden" value="<?php echo $this->category['id']; ?>" name="id">
    <div class="form-group">
        <label class="control-label col-sm-2" for="title">Name:</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="title" placeholder="Name" name="name" required value="<?php echo $this->category['name']; ?>">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-sm-2" for="description">Content:</label>
        <div class="col-sm-10">
            <div class="content">
                <?php echo $this->category['content']; ?>
            </div>
        </div>
    </div>

    <div class="form-group"> 
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>
</form>



