<div class="container container-products">
	<form class="form-horizontal" method="post" action="/products/update" enctype="multipart/form-data">
		<input type="hidden" name="id" value="<?php echo $this->products['id']; ?>">
		<h2>Thay đổi thông tin sản phẩm</h2>
		<div class="form-group">
			<label class="control-label col-sm-3" for="name">Tên sản phẩm:</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" id="name" name="name" required value="<?php echo $this->products['name']; ?>">
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-3" for="description">Mô tả sản phẩm:</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" id="description" name="description" value="<?php echo $this->products['description']; ?>">
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-3" for="images">Ảnh sản phẩm:</label>
			<div class="col-sm-9">
				<input type="file" accept="image/png, image/jpeg, image/gif" id="images" name="image"/>
			</div>
		</div>

		<div class="form-group">
			<label class="control-label col-sm-3" for="price">Giá sản phẩm:</label>
			<div class="col-sm-9">
				<input type="text" class="form-control" id="price" name="price" required value="<?php echo $this->products['price']; ?>">
			</div>
		</div>
		<hr>
		<h2>Quản lý sản phẩm</h2>
		<?php if($_SESSION['type'] == 2):?>
			<?php if($this->products['status'] == 1):?>
				<td><button class="btn btn-danger " type="submit" name="status" value="0" onclick="return confirm('Ngừng đăng sản phẩm này?')">Ngừng đăng sản phẩm</button></td>
			<?php endif;?>
			<?php if($this->products['status'] == 0):?>
				<td><button class="btn btn-primary" type="submit" name="status" value="1" onclick="return confirm('Đăng sản phẩm này?')">Đăng sản phẩm</button></td>
			<?php endif;?>
		<?php endif;?>
		<div class="form-group"> 
			<div class="col-sm-12">
				<button type="submit" class="btn btn-success center-block">THAY ĐỔI</button>
			</div>
		</div>
	</form>
</div>
<div id="updated_content" style="display: none;"><?php echo $this->updated_content; ?></div>
<script type="text/javascript">
	var content = $('#updated_content').text().replace(/\|/g, '\n');		
	console.log(content);
	if(content.trim().length > 0)
		alert(content);
</script>
<?php
echo $this->partial("layout/modal_notice.phtml", array('title' => 'Notice',));
?>