<div id="modal_control" class="modal fade" role="dialog" data-backdrop="static" data-id="">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo $this->title; ?></h4>
            </div>
            <div class="modal-body">Xóa thông tin?</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-info action">Ok</button>
            </div>
        </div>

    </div>
</div>