<div class="container container-products">
    <div class="contentVMT">
        <h3>Tạo Câu lạc bộ mới</h3>
        <form class="form-horizontal new" method="post" action="/clubs/create">
            <?php if($this->message != NULL):?>
                <div class="alert alert-danger">
                  <?php echo $this->message;?>
              </div>
          <?php endif;?>
          <div class="form-group">
            <label class="control-label col-sm-3" for="name">Tên Câu lạc bộ:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="name" placeholder="Nhập tên CLB" name="name" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="description">Mô tả về Câu lạc bộ:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="description" placeholder="Nhập mô tả về CLB" name="description">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="rule_description">Quyền lợi câu lạc bộ:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="rule_description" placeholder="Nhập quyền lợi CLB" name="rule_description" required>
            </div>
        </div>   
        <button type="submit" class="btn btn-success center-block new">ĐĂNG KÝ</button>
    </form>
</div>
</div>