<div class="container">
    <div class="col-lg-3 col-md-3 col-sm-3 col-sx-12 menuAdmin">
        <ul><a href="" ><span class="glyphicon glyphicon-home"></span> Home</a>
            <li><a href="/clubs/show">Thông tin CLB mới</a></li>
            <li><a href="/products/show">Thông tin sản phẩm & dịch vụ</a></li>
            <li><a href="/admin/show">Thông báo từ VFTek</a></li>
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-user"></span> Quản trị người dùng</a>
            <li><a href="/user/">Danh sách người dùng</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-group"></span> Quản trị CLB</a>
            <li><a href="/clubs/new">Thêm CLB mới</a></li>
            <li><a href="/clubs/">Danh sách CLB</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị sản phẩm</a>
            <li><a href="/products/new">Thêm sản phẩm mới</a></li>
            <li><a href="/products/">Danh sách sản phẩm</a></li> 
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị cửa hàng</a>
            <li><a href="/store/new">Thêm cửa hàng mới</a></li>
            <li><a href="/store/">Danh sách cửa hàng</a></li> 
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-cog"></span> Settings</a>
            <li><a href="">xxx</a></li>
            <li><a href="">xxx</a></li>
        </ul>
        <ul><a href="" class="">VOC</a>
            <li><a href="">Gửi phản hồi</a></li>
            <li><a href="">Danh sách phản hồi của bạn</a></li>
        </ul>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-sx-12 contentAdmin">
        <h3>Tạo Câu lạc bộ mới</h3>
        <form class="form-horizontal new" method="post" action="/clubs/create">
            <?php if($this->message != NULL):?>
                <div class="alert alert-danger">
                  <?php echo $this->message;?>
              </div>
          <?php endif;?>
          <div class="form-group">
            <label class="control-label col-sm-3" for="name">Tên Câu lạc bộ:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="name" placeholder="Nhập tên CLB" name="name" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="description">Mô tả về Câu lạc bộ:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="description" placeholder="Nhập mô tả về CLB" name="description">
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3" for="rule_description">Quyền lợi câu lạc bộ:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="rule_description" placeholder="Nhập quyền lợi CLB" name="rule_description" required>
            </div>
        </div>   
        <button type="submit" class="btn btn-success center-block new">ĐĂNG KÝ</button>
    </form>
</div>
</div>
