<div class="container">
    <div class="col-lg-3 col-md-3 col-sm-3 col-sx-12 menuAdmin">
        <ul><a href="" ><span class="glyphicon glyphicon-home"></span> Home</a>
            <li><a href="/clubs/show">Thông tin CLB mới</a></li>
            <li><a href="/products/show">Thông tin sản phẩm & dịch vụ</a></li>
            <li><a href="/admin/show">Thông báo từ VFTek</a></li>
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-user"></span> Quản trị người dùng</a>
            <li><a href="/user/">Danh sách người dùng</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-group"></span> Quản trị CLB</a>
            <li><a href="/clubs/new">Thêm CLB mới</a></li>
            <li><a href="/clubs/">Danh sách CLB</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị sản phẩm</a>
            <li><a href="/products/new">Thêm sản phẩm mới</a></li>
            <li><a href="/products/">Danh sách sản phẩm</a></li> 
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị cửa hàng</a>
            <li><a href="/store/new">Thêm cửa hàng mới</a></li>
            <li><a href="/store/">Danh sách cửa hàng</a></li> 
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-cog"></span> Cài đặt</a>
            <li><a href="">xxx</a></li>
            <li><a href="">xxx</a></li>
        </ul>
        <ul><a href="" class="">VOC</a>
            <li><a href="">Gửi phản hồi</a></li>
            <li><a href="">Danh sách phản hồi của bạn</a></li>
        </ul>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-sx-12 contentAdmin">
        <h3>CLB mới đăng ký</h3>
        <div class="row"></div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Tên thành viên</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php
                $order = 1;
                foreach ($this->club_has_user as $users):
                    ?>
                    <tr id="users-<?php echo $users['id']; ?>">
                        <td><?php echo $order++; ?></td>
                        <td class="id"><?php echo $users['id']; ?></td>
                        <td class="name title"><a href="/index/edit?id=<?php echo $users['id']; ?>"><?php echo $users['name']; ?></a></td>
                        <td><a href="/index/edit?id=<?php echo $users['id']; ?>">Edit</a></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<?php
echo $this->partial("layout/modal_info.phtml", array('title' => 'Upload users', 'action' => '/users/',
    'fields' => array('name' => array('type' => 'fileUpload', 'option' => 'Paper')),
    'controller_name' => 'users'));
echo $this->partial("layout/modal_remove.phtml", array('title' => 'Remove users '));