<div class="container">
    <div class="col-lg-3 col-md-3 col-sm-3 col-sx-12 menuAdmin">
        <ul><a href="" ><span class="glyphicon glyphicon-home"></span> Home</a>
            <li><a href="">Thông tin CLB mới</a></li>
            <li><a href="">Thông tin sản phẩm & dịch vụ</a></li>
            <li><a href="">Thông báo từ VFTek</a></li>
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-user"></span> Quản trị người dùng</a>
            <li><a href="/user/">Danh sách người dùng</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-group"></span> Quản trị CLB</a>
            <li><a href="/clubs/new">Thêm CLB mới</a></li>
            <li><a href="/clubs/">Danh sách CLB</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị sản phẩm</a>
            <li><a href="/products/new">Thêm sản phẩm mới</a></li>
            <li><a href="/products/">Danh sách sản phẩm</a></li> 
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị cửa hàng</a>
            <li><a href="/store/new">Thêm sản cửa hàng</a></li>
            <li><a href="/store/">Danh sách cửa hàng</a></li> 
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-cog"></span> Settings</a>
            <li><a href="">xxx</a></li>
            <li><a href="">xxx</a></li>
        </ul>
        <ul><a href="" class="">VOC</a>
            <li><a href="">Gửi phản hồi</a></li>
            <li><a href="">Danh sách phản hồi của bạn</a></li>
        </ul>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-sx-12 contentAdmin">
        <form class="form-horizontal" method="post" action="/store/update">
            <input type="hidden" name="id" value="<?php echo $this->store['id']; ?>">
            <h2>Thay đổi thông tin cửa hàng</h2>
            <div class="form-group">
                <label class="control-label col-sm-3" for="name">Tên cửa hàng</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="name" name="name" required value="<?php echo $this->store['name']; ?>">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="description">Mô tả cửa hàng:</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="description" name="description" value="<?php echo $this->store['description']; ?>">
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-sm-3" for="address">Địa chỉ cửa hàng</label>
                <div class="col-sm-9">
                    <input type="text" class="form-control" id="address" name="address" required value="<?php echo $this->store['address']; ?>">
                </div>
            </div>
            <div class="form-group"> 
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-success center-block">THAY ĐỔI</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div id="updated_content" style="display: none;"><?php echo $this->updated_content; ?></div>
<script type="text/javascript">
    var content = $('#updated_content').text().replace(/\|/g, '\n');        
    console.log(content);
    if(content.trim().length > 0)
        alert(content);
</script>
<?php
echo $this->partial("layout/modal_notice.phtml", array('title' => 'Notice',));
?>