<div class="container container-products">
    <form class="form-horizontal" method="post" action="/store/update">
        <input type="hidden" name="id" value="<?php echo $this->store['id']; ?>">
        <h2>Thay đổi thông tin cửa hàng</h2>
        <div class="form-group">
            <label class="control-label col-sm-3" for="name">Tên cửa hàng</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="name" name="name" required value="<?php echo $this->store['name']; ?>">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="description">Mô tả cửa hàng:</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="description" name="description" value="<?php echo $this->store['description']; ?>">
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-3" for="address">Địa chỉ cửa hàng</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" id="address" name="address" required value="<?php echo $this->store['address']; ?>">
            </div>
        </div>
        <div class="form-group"> 
            <div class="col-sm-12">
                <button type="submit" class="btn btn-success center-block">THAY ĐỔI</button>
            </div>
        </div>
    </form>
</div>
<div id="updated_content" style="display: none;"><?php echo $this->updated_content; ?></div>
<script type="text/javascript">
    var content = $('#updated_content').text().replace(/\|/g, '\n');        
    console.log(content);
    if(content.trim().length > 0)
        alert(content);
</script>
<?php
echo $this->partial("layout/modal_notice.phtml", array('title' => 'Notice',));
?>