<div class="container">
    <div class="col-lg-3 col-md-3 col-sm-3 col-sx-12 menuAdmin">
        <ul><a href="" ><span class="glyphicon glyphicon-home"></span> Home</a>
           <li><a href="/clubs/show">Thông tin CLB mới</a></li>
            <li><a href="/products/show">Thông tin sản phẩm & dịch vụ</a></li>
            <li><a href="/admin/show">Thông báo từ VFTek</a></li>
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-user"></span> Quản trị người dùng</a>
            <li><a href="/user/">Danh sách người dùng</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-group"></span> Quản trị CLB</a>
            <li><a href="/clubs/new">Thêm CLB mới</a></li>
            <li><a href="/clubs/">Danh sách CLB</a></li>
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị sản phẩm</a>
            <li><a href="/products/new">Thêm sản phẩm mới</a></li>
            <li><a href="/products/">Danh sách sản phẩm</a></li> 
        </ul>
        <ul><a href="" class=""><span class="fa fa-product-hunt"></span> Quản trị cửa hàng</a>
            <li><a href="/store/new">Thêm cửa hàng mới</a></li>
            <li><a href="/store/">Danh sách cửa hàng</a></li> 
        </ul>
        <ul><a href="" class=""><span class="glyphicon glyphicon-cog"></span> Settings</a>
            <li><a href="">xxx</a></li>
            <li><a href="">xxx</a></li>
        </ul>
        <ul><a href="" class="">VOC</a>
            <li><a href="">Gửi phản hồi</a></li>
            <li><a href="">Danh sách phản hồi của bạn</a></li>
        </ul>
    </div>
    <div class="col-lg-9 col-md-9 col-sm-9 col-sx-12 contentAdmin">
        <h3>Thêm cửa hàng mới</h3>
        <form action="/store/create" method="post" enctype="multipart/form-data">
            <table class="table table-bordered">
                <tr>
                    <td>Tên cửa hàng:</td>
                    <td>
                        <div class="form-group">
                            <input type="text" class="form-control" name="store[name]" value="" required>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Mô tả cửa hàng:</td>
                    <td>
                        <div class="form-group">
                            <input type="text" class="form-control" name="store[description]" value="" required>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Địa chỉ cửa hàng:</td>
                    <td>
                        <div class="form-group">
                            <input type="text" class="form-control" name="store[address]" value="" required>
                        </div>
                    </td>
                </tr>
            </table>           
            <button class="btn btn-success" type="submit" name="save">TẠO MỚI</button>
        </form>
    </div>
</div>
