<div id="modal_info" class="modal fade" role="dialog" data-backdrop="static" data-controller-name="<?php echo $this->controller_name ?>">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title"><?php echo $this->title; ?></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" action="<?php echo $this->action ?>" method="POST" enctype="multipart/form-data">
                    <input type="hidden" name="id">
                    <?php foreach ($this->fields as $lable => $name): ?>
                        <?php if (is_array($name)): ?>
                            <?php echo $this->partial('layout/' . $name['type'] . '.phtml', array('name' => $lable, 'option' => $name['option'], 'class'=>$name['class'])) ?>
                        <?php elseif (!empty($name)): ?>
                            <div class="form-group">
                                <label for="input<?php echo $name; ?>" class="col-sm-2 control-label"><?php echo $lable; ?></label>
                                <div class="col-sm-10">
                                    <input type="text" class="form-control" id="input<?php echo $name; ?>" placeholder="<?php echo $lable; ?>" name="<?php echo $name; ?>">
                                </div>
                            </div>
                        <?php endif; ?>

                    <?php endforeach; ?>
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10"><p class="error-notifice"></p></div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cannel</button>
                <button type="button" class="btn btn-info save_object">Save</button>
            </div>
        </div>

    </div>
</div>