<div class="search">
    <div class="form-horizontal show-less">
        <?php $index = 0; ?>
        <?php foreach ($this->fields as $lable => $value): ?>
            <div class="form-group">
                <?php if (is_array($value)): ?>
                    <?php echo $this->partial('layout/search/' . $value['type'] . '.phtml', array('name' => $lable, 'option' => $value['option'])) ?>
                <?php else: ?>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" placeholder="<?php echo $value ?>" name="<?php echo $lable; ?>">
                    </div>
                <?php endif; ?>
                <?php if ($index == 0): ?>
                <button class="btn btn-primary col-sm-2" id="search">Search</button>
                <?php endif; ?>
            </div>
            <?php $index++; ?>

        <?php endforeach; ?>
    </div>
    <div class="col-sm-12">
        <div  class="pull-right"><a id="show-control" href="#">Show more</a></div>
    </div>
</div>
<div class="col-sm-12" id="search-notify"></div>